version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: local_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - booking_service
      - payment_service
      - flight_service
    networks:
      - airplane_net
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airplane_net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - airplane_net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - airplane_net
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:2.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - airplane_net
    restart: unless-stopped

  kafka_topic_init:
    image: bitnami/kafka:2.7.0
    container_name: kafka_topic_init
    depends_on:
      - kafka
    entrypoint: [ "/bin/bash", "-c" ]
    command: >
      "sleep 20 &&
       kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic add-booking &&
       kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic confirm-booking &&
       kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic failed-add-booking &&
       kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic failed-confirm-booking"
    networks:
      - airplane_net
    restart: "no"

  cron_service:
    build:
      context: .
      dockerfile: ./images/cron/Dockerfile
    container_name: cron_service
    expose:
      - "8081"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_topic_init:
        condition: service_completed_successfully
    networks:
      - airplane_net
    restart: unless-stopped


  qworker_service:
    build:
      context: .
      dockerfile: ./images/qworker/Dockerfile
    container_name: qworker_service
    expose:
      - "8082"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_topic_init:
        condition: service_completed_successfully
    networks:
      - airplane_net
    restart: unless-stopped

  booking_service:
    build:
      context: .
      dockerfile: ./images/booking/Dockerfile
    container_name: booking_service
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_topic_init:
        condition: service_completed_successfully
    networks:
      - airplane_net
    restart: unless-stopped

  payment_service:
    build:
      context: .
      dockerfile: ./images/payment/Dockerfile
    container_name: payment_service
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_topic_init:
        condition: service_completed_successfully
    networks:
      - airplane_net
    restart: unless-stopped

  flight_service:
    build:
      context: .
      dockerfile: ./images/flight/Dockerfile
    container_name: flight_service
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_topic_init:
        condition: service_completed_successfully
    networks:
      - airplane_net
    restart: unless-stopped

volumes:
  mysql_data:
  kafka_data:

networks:
  airplane_net:
    driver: bridge