### Get Flight List
GET http://localhost/api/v1/flight
Accept: application/json

###
GET http://localhost/api/v1/flight?departureAirport=NRT&arrivalAirport=KIX&departureTimeStartAt=2025-04-01T00:00:00Z&departureTimeEndAt=2025-04-01T23:59:59Z&pi=1&ps=10
Accept: application/json

###

### Create Booking
POST http://localhost/api/v1/booking
Content-Type: application/json

{
  "flightID": 2001,
  "cabinClassID": 3002,
  "email": "test1@example.com",
  "countryCode": "886",
  "phoneNumber": "912345671",
  "seatID": 4003
}

###

### Get Booking
GET http://localhost/api/v1/booking/295916500769382400
Accept: application/json

###

### Edit Booking
PATCH http://localhost/api/v1/booking/5002
Content-Type: application/json

{
  "cabinClassID": 3002,
  "seatID": 4004
}

###

### Cancel Booking
DELETE http://localhost/api/v1/booking/5003
Accept: application/json

###

### Notify Payment
POST http://localhost/api/v1/payment/notify
Content-Type: application/json

{
  "id": "295916507165138944",
  "paidAt": "2025-03-26T13:00:00Z",
  "method": "credit_card",
  "provider": "stripe",
  "status": "success",
  "transactionID": "txn_423456789"
}