
@startuml
actor User
User -> BookingService: EditBooking
activate BookingService

BookingService -> BookingDAO: Get(booking.ID)
activate BookingDAO
BookingDAO -> BookingService: Return booking
deactivate BookingDAO

alt Booking.Status is Cancelled, Expired, Confirming
    BookingService -> User: Error - Status Not Match
    deactivate BookingService
else SeatID has not changed
    BookingService -> User: No Change Required
    deactivate BookingService
else SeatID has changed
    BookingService -> SeatDAO: Get(cond.SeatID)
    activate SeatDAO
    SeatDAO -> BookingService: Return new seat
    deactivate SeatDAO

    BookingService -> CabinClassDAO: Get(cond.CabinClassID)
    activate CabinClassDAO
    CabinClassDAO -> BookingService: Return new class
    deactivate CabinClassDAO

    BookingService -> PaymentDAO: GetByBookingID(booking.ID)
    activate PaymentDAO
    PaymentDAO -> BookingService: Return payment
    deactivate PaymentDAO

    alt Booking.Status == Pending
        BookingService -> PaymentDAO: UpdateAmount(payment.ID, newClass.Price)
        activate PaymentDAO
        PaymentDAO -> BookingService: Updated
        deactivate PaymentDAO
    else Booking.Price != newClass.Price
        BookingService -> ExtraPaymentDAO: Create(extraPayment)
        activate ExtraPaymentDAO
        ExtraPaymentDAO -> BookingService: Extra Payment Created
        deactivate ExtraPaymentDAO

        BookingService -> SeatDAO: Update(newSeat.ID, Status.Held)
        activate SeatDAO
        SeatDAO -> BookingService: Seat Updated
        deactivate SeatDAO
        BookingService -> BookingService: Set Booking.Status to Confirming
    else
        BookingService -> SeatDAO: Update(newSeat.ID, Status.Booked)
        activate SeatDAO
        SeatDAO -> BookingService: Seat Updated
        deactivate SeatDAO
        BookingService -> BookingService: Set Booking.Status to Confirmed
    end

    BookingService -> BookingDAO: UpdateSeat(booking.ID, newSeat.ID, newClass.ID, newClass.Price)
    activate BookingDAO
    BookingDAO -> BookingService: Booking Updated
    deactivate BookingDAO
    BookingService -> User: Booking Edited Successfully
end

deactivate BookingService
@enduml
